main: com.ricemarch.AuthMeow
version: 0.1
api-version: 1.16
name: AuthMeow
commands:
  login:
    aliases:
      - "lg"
      - "l"
      - "L"
    description: "Login or register"
    usage: "/login <PASSWORD>"